// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPOs4SrdPWvtij9TZuvJxUsLOytuI0xoY',
    appId: '1:1041840353254:web:167a2cc9abbae397317027',
    messagingSenderId: '1041840353254',
    projectId: 'fk-portfolio',
    authDomain: 'fk-portfolio.firebaseapp.com',
    storageBucket: 'fk-portfolio.firebasestorage.app',
    measurementId: 'G-T3EE9Y3C7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAd5mDnoXgLGJeRwOiPS9Nz8Fg89EvRi8',
    appId: '1:1041840353254:android:afbc0df184b7a1a1317027',
    messagingSenderId: '1041840353254',
    projectId: 'fk-portfolio',
    storageBucket: 'fk-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKcWHFLVF7MT2qoLBzpMRQZI8C16TzJQ',
    appId: '1:1041840353254:ios:d44fe976652ad5ab317027',
    messagingSenderId: '1041840353254',
    projectId: 'fk-portfolio',
    storageBucket: 'fk-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.fkProtfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnKcWHFLVF7MT2qoLBzpMRQZI8C16TzJQ',
    appId: '1:1041840353254:ios:d44fe976652ad5ab317027',
    messagingSenderId: '1041840353254',
    projectId: 'fk-portfolio',
    storageBucket: 'fk-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.fkProtfolio',
  );
}
